name: test

on:
  workflow_dispatch:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      color: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
      - name: Get color
        run: echo "color is ${{needs.job1.outputs.color}}"
    
