name: test

run-name: update prod image

on:
  workflow_dispatch:
    inputs:
      sha:
        description: '手动指定提交hash'
        required: false

jobs:
  test_and_build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
          
      - name: Retrieve version
        run: |
          if git rev-parse "${{ inputs.sha }}"; then
            SHA=$(git rev-parse "${{ inputs.sha }}" 2>/dev/null)
            TYPE=$(git cat-file -t "$SHA")
            if [ "$TYPE" = "commit" ]; then
              echo "IMAGE_TAG=$SHA" >> $GITHUB_OUTPUT
            else
              echo "SHA ${{ inputs.sha }} is not a commit"
            fi
          else
            echo "SHA ${{ inputs.sha }} is not a valid commit."
          fi
        id: version

      - name: Checkout ArgoCD app repository
        run: |
          echo ${{ steps.version.outputs.IMAGE_TAG }}
