name: test

on:
  workflow_dispatch:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve version
      run: |
        echo "UAT_SHA=$(git rev-parse ${{ vars.UAT_BRANCH }})" >> $GITHUB_OUTPUT
      id: version
    - name: Test
      run: |
        echo ${{ steps.version.outputs.SHA }}
